title: Daniel Solis
logo: /assets/img/foto_circ.png
include:
  - _includes/head.html
description: >
  <br>
  Data Scientist with 2+ years of professional experience. I am specialized in computational physics. I have experience in mathematical modeling, machine learning, deep learning, high performance computing and deployment of ML applications. 
  <br>
  <br>
github: 
  is_user_page: true
google_analytics: true  
theme: jekyll-theme-minimal
