title: Daniel Solis
logo: /assets/img/foto_circ.png
description: >
  <br>
  Data Scientist with 2+ years of professional experience. I am specialized in computational physics. I have experience in mathematical modeling, machine learning, deep learning, high performance computing and deployment of ML applications. 
  <br>
  <a href="https://www.linkedin.com/in/daniel-solis-phd-323513154/">View my LinkedIn Profile</a>
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/danalejosolerma
  another_url: another value
